version: "3.8"
services:
  robotoald:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./alerts.db:/app/alerts.db
      - ./batphone.ini:/app/batphone.ini
      - ./certs:/app/certs  # Bind local certs directory

    restart: always
    ports:
      # Expose API port (adjust if your API runs on a different port)
      - "9443:9443"

