version: "3.8"
services:
  robotoald:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./batphone.ini:/app/batphone.ini
      - ./certs:/app/certs
      - ./audit_archives:/app/audit_archives
      - ./google_service_config.json:/app/google_service_config.json

    restart: always
    ports:
      # Expose API port only on localhost (127.0.0.1)
      - "127.0.0.1:5998:8080"

