version: "3.8"
services:
  robotoald:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./alerts.db:/app/alerts.db
      - ./batphone.ini:/app/batphone.ini
    restart: always
