"""account characters

Revision ID: a1f30d402711
Revises: 49a9dc0a9b66
Create Date: 2025-11-09 08:04:17.694788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f30d402711'
down_revision: Union[str, None] = '49a9dc0a9b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_account_character',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('class',
              sa.Enum('Bard', 'Cleric', 'Druid', 'Enchanter', 'Magician', 'Monk', 'Necromancer', 'Paladin',
                      'Ranger', 'Rogue', 'ShadowKnight', 'Shaman', 'Warrior', 'Wizard', name='characterclass'),
              nullable=False),
    sa.Column('bind_location', sa.String(length=64), nullable=True),
    sa.Column('park_location', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sso_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'guild_id', name='uq_name_guild')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sso_account_character')
    # ### end Alembic commands ###
